use collections = "collections"

class Message
    """
    Represents a message sent in a channel within Discord.
    """

    let id: Snowflake
        """
        id of the message
        """

    let channel_id: Snowflake
        """
        id of the channel the message was sent in
        """

    // TODO(vxern): This may need to be a union between user and webhook user.
    let author: User
        """
        user object	the author of this message

        The author object follows the structure of the user object, but is only a valid user in the case where the message is generated by a user or bot user. If the message is generated by a webhook, the author object corresponds to the webhook’s id, username, and avatar. You can tell if a message is generated by a webhook by checking for the webhook_id on the message object.
        """

    let content: String
        """
        contents of the message

        An app will receive empty values in the content, embeds, attachments, and components fields while poll will be omitted if they have not configured (or been approved for) the MESSAGE_CONTENT privileged intent (1 << 15).
        """

    let timestamp: ISO8601
        """
        when this message was sent
        """

    let edited_timestamp: (ISO8601 | None)
        """
        when this message was edited (or null if never)
        """

    let tts: Bool
        """
        whether this was a TTS message
        """

    let mention_everyone: Bool
        """
        whether this message mentions everyone
        """

    let mentions: Array[User]
        """
        users specifically mentioned in the message
        """

    let mention_roles: Array[Snowflake]
        """
        roles specifically mentioned in this message
        """

    let mention_channels: (Array[ChannelMention] | None)
        """
        channels specifically mentioned in this message

        Not all channel mentions in a message will appear in mention_channels. Only textual channels that are visible to everyone in a public guild will ever be included. Only crossposted messages (via Channel Following) currently include mention_channels at all. If no mentions in the message meet these requirements, this field will not be sent.
        """

    let attachments: Array[MessageAttachment]
        """
        any attached files that are not referenced in embeds or components

        An app will receive empty values in the content, embeds, attachments, and components fields while poll will be omitted if they have not configured (or been approved for) the MESSAGE_CONTENT privileged intent (1 << 15).
        """

    let embeds: Array[MessageEmbed]
        """
        any embedded content

        An app will receive empty values in the content, embeds, attachments, and components fields while poll will be omitted if they have not configured (or been approved for) the MESSAGE_CONTENT privileged intent (1 << 15).
        """

    let reactions: (Array[MessageReaction] | None)
        """
        reactions to the message
        """

    let nonce: (USize | String | None)
        """
        used for validating a message was sent
        """

    let pinned: Bool
        """
        whether this message is pinned
        """

    let webhook_id: (Snowflake | None)
        """
        if the message is generated by a webhook, this is the webhook’s id
        """

    let type': MessageType
        """
        if the message is generated by a webhook, this is the webhook’s id
        """

    let activity: (MessageActivity | None)
        """
        sent with Rich Presence-related chat embeds
        """

    // TODO(vxern): This is actually a partial application.
    let application: (Application | None)
        """
        sent with Rich Presence-related chat embeds
        """

    let application_id: (Snowflake | None)
        """
        if the message is an Interaction or application-owned webhook, this is the id of the application
        """

    let flags: (Array[MessageFlag] | None)
        """
        message flags combined as a bitfield
        """

    let message_reference: (MessageReference | None)
        """
        data showing the source of a crosspost, channel follow add, pin, or reply message
        """

    let message_snapshots: (Array[MessageSnapshot] | None)
        """
        the message associated with the message_reference. This is a minimal subset of fields in a message (e.g. author is excluded.)

        This field is only returned for messages with a type of 19 (REPLY), 21 (THREAD_STARTER_MESSAGE), or 23 (CONTEXT_MENU_COMMAND). If the message is one of these but the referenced_message field is not present, the backend did not attempt to fetch the message that was being replied to, so its state is unknown. If the field exists but is null, the referenced message was deleted.
        """

    // TODO(vxern): Is this a partial message?
    let referenced_message: (Message | None)
        """
        the message associated with the message_reference

        This field is only returned for messages with a type of 19 (REPLY), 21 (THREAD_STARTER_MESSAGE), or 23 (CONTEXT_MENU_COMMAND). If the message is one of these but the referenced_message field is not present, the backend did not attempt to fetch the message that was being replied to, so its state is unknown. If the field exists but is null, the referenced message was deleted.
        """

    let interaction_metadata: (ApplicationCommandInteractionMetadata | MessageComponentInteractionMetadata | ModalSubmitInteractionMetadata | None)
        """
        Sent if the message is sent as a result of an interaction
        """

    let interaction: (Interaction | None)
        """
        Deprecated in favor of interaction_metadata; sent if the message is a response to an interaction
        """

    let thread: (Channel | None)
        """
        the thread that was started from this message, includes thread member object
        """

    let components: (Array[Component] | None)
        """
        sent if the message contains components like buttons, action rows, or other interactive components

        An app will receive empty values in the content, embeds, attachments, and components fields while poll will be omitted if they have not configured (or been approved for) the MESSAGE_CONTENT privileged intent (1 << 15).
        """

    let sticker_items: (Array[StickerItem] | None)
        """
        sent if the message contains stickers
        """

    let stickers: (Array[Sticker] | None)
        """
        Deprecated the stickers sent with the message
        """

    let position: (USize | None)
        """
        A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a thread, it can be used to estimate the relative position of the message in a thread in company with total_message_sent on parent thread
        """

    let role_subscription_data: (RoleSubscriptionData | None)
        """
        data of the role subscription purchase or renewal that prompted this ROLE_SUBSCRIPTION_PURCHASE message
        """

    let resolved: (ResolvedData | None)
        """
        data for users, members, channels, and roles referenced in this message
        """

    let poll: (Poll | None)
        """
        A poll!
        
        An app will receive empty values in the content, embeds, attachments, and components fields while poll will be omitted if they have not configured (or been approved for) the MESSAGE_CONTENT privileged intent (1 << 15).
        """

    let call: (MessageCall | None)
        """
        the call associated with the message
        """

    let shared_client_theme: (SharedClientTheme | None)
        """
        the custom client-side theme shared via the message
        """

trait val MessageType is (collections.Hashable & Equatable[MessageType])
    fun value(): U8

	fun deletable(): Bool

    fun hash(): USize => value().hash()

    fun eq(that: MessageType): Bool => value() == that.value()
primitive DefaultMessageType is MessageType
    fun value(): U8 => 0

	fun deletable(): Bool => true
primitive RecipientAddMessageType is MessageType
    fun value(): U8 => 1

	fun deletable(): Bool => false
primitive RecipientRemoveMessageType is MessageType
    fun value(): U8 => 2

	fun deletable(): Bool => false
primitive CallMessageType is MessageType
    fun value(): U8 => 3

	fun deletable(): Bool => false
primitive ChannelNameChangeMessageType is MessageType
    fun value(): U8 => 4

	fun deletable(): Bool => false
primitive ChannelIconChangeMessageType is MessageType
    fun value(): U8 => 5

	fun deletable(): Bool => false
primitive ChannelPinnedMessageMessageType is MessageType
    fun value(): U8 => 6

	fun deletable(): Bool => true
primitive UserJoinMessageType is MessageType
    fun value(): U8 => 7

	fun deletable(): Bool => true
primitive GuildBoostMessageType is MessageType
    fun value(): U8 => 8

	fun deletable(): Bool => true
primitive GuildBoostTier1MessageType is MessageType
    fun value(): U8 => 9

	fun deletable(): Bool => true
primitive GuildBoostTier2MessageType is MessageType
    fun value(): U8 => 10

	fun deletable(): Bool => true
primitive GuildBoostTier3MessageType is MessageType
    fun value(): U8 => 11

	fun deletable(): Bool => true
primitive ChannelFollowAddMessageType is MessageType
    fun value(): U8 => 12

	fun deletable(): Bool => true
primitive GuildDiscoveryDisqualifiedMessageType is MessageType
    fun value(): U8 => 14

	fun deletable(): Bool => true
primitive GuildDiscoveryRequalifiedMessageType is MessageType
    fun value(): U8 => 15

	fun deletable(): Bool => true
primitive GuildDiscoveryGracePeriodInitialWarningMessageType is MessageType
    fun value(): U8 => 16

	fun deletable(): Bool => true
primitive GuildDiscoveryGracePeriodFinalWarningMessageType is MessageType
    fun value(): U8 => 17

	fun deletable(): Bool => true
primitive ThreadCreatedMessageType is MessageType
    fun value(): U8 => 18

	fun deletable(): Bool => true
primitive ReplyMessageType is MessageType
    fun value(): U8 => 19

	fun deletable(): Bool => true
primitive ChatInputCommandMessageType is MessageType
    fun value(): U8 => 20

	fun deletable(): Bool => true
primitive ThreadStarterMessageType is MessageType
    fun value(): U8 => 21

	fun deletable(): Bool => false
primitive GuildInviteReminderMessageType is MessageType
    fun value(): U8 => 22

	fun deletable(): Bool => true
primitive ContextMenuCommandMessageType is MessageType
    fun value(): U8 => 23

	fun deletable(): Bool => true
primitive AutoModerationActionMessageType is MessageType
    """
    Can only be deleted by members with MANAGE_MESSAGES permission
    """

    fun value(): U8 => 24

	fun deletable(): Bool => true
primitive RoleSubscriptionPurchaseMessageType is MessageType
    fun value(): U8 => 25

	fun deletable(): Bool => true
primitive InteractionPremiumUpsellMessageType is MessageType
    fun value(): U8 => 26

	fun deletable(): Bool => true
primitive StageStartMessageType is MessageType
    fun value(): U8 => 27

	fun deletable(): Bool => true
primitive StageEndMessageType is MessageType
    fun value(): U8 => 28

	fun deletable(): Bool => true
primitive StageSpeakerMessageType is MessageType
    fun value(): U8 => 29

	fun deletable(): Bool => true
primitive StageTopicMessageType is MessageType
    fun value(): U8 => 31

	fun deletable(): Bool => true
primitive GuildApplicationPremiumSubscriptionMessageType is MessageType
    fun value(): U8 => 32

	fun deletable(): Bool => true
primitive GuildIncidentAlertModeEnabledMessageType is MessageType
    fun value(): U8 => 36

	fun deletable(): Bool => true
primitive GuildIncidentAlertModeDisabledMessageType is MessageType
    fun value(): U8 => 37

	fun deletable(): Bool => true
primitive GuildIncidentReportRaidMessageType is MessageType
    fun value(): U8 => 38

	fun deletable(): Bool => true
primitive GuildIncidentReportFalseAlartMessageType is MessageType
    fun value(): U8 => 39

	fun deletable(): Bool => true
primitive PurchaseNotificationMessageType is MessageType
    fun value(): U8 => 44

	fun deletable(): Bool => true
primitive PollResultMessageType is MessageType
    fun value(): U8 => 46

	fun deletable(): Bool => true

class MessageActivity
    """
    type of message activity
    """
    let type': MessageActivityType
    
    """
    party_id from a Rich Presence event
    """
    let party_id: String

trait val MessageActivityType is (collections.Hashable & Equatable[MessageActivityType])
    fun value(): U8
    fun hash(): USize => value().hash()
    fun eq(that: MessageActivityType): Bool => value() == that.value()
primitive JoinMessageActivityType is MessageActivityType
    fun value(): U8 => 1
primitive SpectateMessageActivityType is MessageActivityType
    fun value(): U8 => 2
primitive ListenMessageActivityType is MessageActivityType
    fun value(): U8 => 3
primitive JoinRequestMessageActivityType is MessageActivityType
    fun value(): U8 => 5

trait val MessageFlag is (collections.Hashable & Equatable[MessageFlag])
    fun value(): U8
        """
        Represents the bit-shift value. Unshift by this value to get the flag.
        """

    fun hash(): USize => value().hash()

    fun eq(that: MessageFlag): Bool => value() == that.value()
primitive CrosspostedMessageFlag is MessageFlag
    """
    this message has been published to subscribed channels (via Channel Following)
    """

    fun value(): U8 => 0
primitive IsCrosspostMessageFlag is MessageFlag
    """
    this message originated from a message in another channel (via Channel Following)
    """

    fun value(): U8 => 1
primitive SuppressEmbedsMessageFlag is MessageFlag
    """
    do not include any embeds when serializing this message
    """

    fun value(): U8 => 2
primitive SourceMessageDeletedMessageFlag is MessageFlag
    """
    the source message for this crosspost has been deleted (via Channel Following)
    """

    fun value(): U8 => 3
primitive UrgentMessageFlag is MessageFlag
    """
    this message came from the urgent message system
    """

    fun value(): U8 => 4
primitive HasThreadMessageFlag is MessageFlag
    """
    this message has an associated thread, with the same id as the message
    """

    fun value(): U8 => 5
primitive EphemeralMessageFlag is MessageFlag
    """
    this message is only visible to the user who invoked the Interaction
    """

    fun value(): U8 => 6
primitive LoadingMessageFlag is MessageFlag
    """
    this message is an Interaction Response and the bot is “thinking”
    """

    fun value(): U8 => 7
primitive FailedToMentionSomeRolesInThreadMessageFlag is MessageFlag
    """
    this message failed to mention some roles and add their members to the thread
    """

    fun value(): U8 => 8
primitive SuppressNotificationsMessageFlag is MessageFlag
    """
    this message will not trigger push and desktop notifications
    """

    fun value(): U8 => 12
primitive IsVoiceMessageMessageFlag is MessageFlag
    """
    this message is a voice message
    """

    fun value(): U8 => 13
primitive HasSnapshotMessageFlag is MessageFlag
    """
    this message has a snapshot (via Message Forwarding)
    """

    fun value(): U8 => 14
primitive IsComponentsV2MessageFlag is MessageFlag
    """
    allows you to create fully component-driven messages

    Once a message has been sent with this flag, it can’t be removed from that message.
    """

    fun value(): U8 => 15

class ApplicationCommandInteractionMetadata
    """
    Metadata about the interaction, including the source of the interaction and relevant server and user IDs.
    """
    // TODO(vxern): Implement.

class MessageComponentInteractionMetadata
    """
    Metadata about the interaction, including the source of the interaction and relevant server and user IDs.
    """
    // TODO(vxern): Implement.

class ModalSubmitInteractionMetadata
    """
    Metadata about the interaction, including the source of the interaction and relevant server and user IDs.
    """
    // TODO(vxern): Implement.

class MessageCall
    """
    Information about the call in a private channel.
    """
    // TODO(vxern): Implement.

class MessageReference
    // TODO(vxern): Implement.

// TODO(vxern): Do these need to have the 'Coupled Message Field'?
trait val MessageReferenceType is (collections.Hashable & Equatable[MessageReferenceType])
    """
    Determines how associated data is populated.
    """

    fun value(): U8

    fun hash(): USize => value().hash()

    fun eq(that: MessageReferenceType): Bool => value() == that.value()
primitive DefaultMessageReferenceType
    """
    A standard reference used by replies.
    """

    fun value(): U8 => 0
primitive ForwardMessageReferenceType
    """
    Reference used to point to a message at a point in time.
    """

    fun value(): U8 => 1

class MessageSnapshot
    // TODO(vxern): Implement.

class MessageReaction
    // TODO(vxern): Implement.

class MessageReactionCountDetails
    """
    The reaction count details object contains a breakdown of normal and super reaction counts for the associated emoji."""
    // TODO(vxern): Implement.

class MessageEmbed
    // TODO(vxern): Implement.

trait MessageEmbedType
    // TODO(vxern): Implement.

class MessageEmbedFlag
    // TODO(vxern): Implement.

class MessageEmbedVideo
    // TODO(vxern): Implement.

class MessageEmbedImage
    // TODO(vxern): Implement.

trait MessageEmbedMediaFlag
    // TODO(vxern): Implement.

class MessageEmbedProvider
    // TODO(vxern): Implement.

class MessageEmbedAuthor
    // TODO(vxern): Implement.

class MessageEmbedFooter
    // TODO(vxern): Implement.

class MessageEmbedField
    // TODO(vxern): Implement.

// TODO(vxern): Include embed fields by embed type?

class MessageAttachment
    // TODO(vxern): Implement.

trait MessageAttachmentFlag
    // TODO(vxern): Implement.

class ChannelMention
    // TODO(vxern): Implement.

trait val AllowedMention is (collections.Hashable & Equatable[AllowedMention])
    """
    Setting the allowed_mentions field lets you determine whether users will receive notifications when you include mentions in the message content, or the content of components attached to that message. This field is always validated against your permissions and the presence of said mentions in the message, to avoid “phantom” pings where users receive a notification without a visible mention in the message. For example, if you want to ping everyone, including it in the allowed_mentions field is not enough, the mention format (@everyone) must also be present in the content of the message or its components. It is important to note that setting this field does not guarantee a push notification will be sent, as additional factors can influence this:
    - To mention roles and notify their members, the role’s mentionable field must be set to true, or the bot must have the MENTION_EVERYONE permission
    - To mention @everyone and @here, the bot must have the MENTION_EVERYONE permission
    - Setting the SUPPRESS_NOTIFICATIONS flag when sending a message will disable push notifications and only cause a notification badge
    - Users can customize their notification settings through the Discord app, which might cause them to only receive a notification badge and no push notification
    """

    fun value(): String

    fun hash(): USize => value().hash()

    fun eq(that: AllowedMention): Bool => value() == that.value()
primitive AllowedMentionRole is AllowedMention
    """
    Controls role mentions
    """

    fun value(): String => "roles"
primitive AllowedMentionUser is AllowedMention
    """
    Controls user mentions
    """

    fun value(): String => "users"
primitive AllowedMentionEveryone is AllowedMention
    """
    Controls @everyone and @here mentions
    """

    fun value(): String => "everyone"

class RoleSubscriptionData
    // TODO(vxern): Implement.

class MessagePin
    // TODO(vxern): Implement.

class SharedClientTheme
    // TODO(vxern): Implement.

class BaseThemeType
    // TODO(vxern): Implement.
